Repository deswa7310/E101-AVC-Project-Team-11, pull requests merged in 2020-06, with the labels that each got.

#17 Update and rename Weekly Update 1 to Weekly Update Doc.md
  Weekly Update 1
  Weekly Update Doc.md
Labels: documentation

#19 Update robot.cpp
  Team 11 Robot/robot.cpp
Labels: documentation

#18 Update robot.cpp
  Team 11 Robot/robot.cpp
Labels: enhancement

#24 Update robot.cpp
  Team 11 Robot/robot.cpp
Labels: bug

#31 Final code cleanup
  Team 11 Robot/robot.cpp
Labels: enhancement

#33 Update robot.cpp
  Team 11 Robot/robot.cpp
Labels: documentation, enhancement

#32 Final code clean-up and minor addition
  Team 11 Robot/robot.cpp
Labels: documentation, enhancement

#30 Updated combined program
  Team 11 Robot/robot.cpp
Labels: enhancement
